keyBinds:
  keyUp: I
  keyDown: A
  keyLeft: Q
  keyRight: D
  keyUpLeft: X
  keyUpRight: E
  keyDownLeft: W
  keyDownRight: C
  keyHelp: /
  keyInventory: Z
settings:
  gridColumns: 5
  gridRows: 5
  wallFrequency: 30
  bonusFrequency: 10
  canTeleport: false